# Generated by Django 4.2.5 on 2023-09-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.CharField(default='KAI', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='Aset', max_length=255),
            preserve_default=False,
        ),
    ]
